// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SacramentPlanner.Models;
using System;

namespace SacramentPlanner.Migrations
{
    [DbContext(typeof(SacramentPlannerContext))]
    [Migration("20180713004318_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("SacramentPlanner.Models.SacProgram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClosingPrayer");

                    b.Property<string>("ClosingSong");

                    b.Property<string>("Conducting");

                    b.Property<DateTime>("Date");

                    b.Property<string>("FirstSpeaker");

                    b.Property<string>("IntermediateSong");

                    b.Property<string>("OpeningPrayer");

                    b.Property<string>("OpeningSong");

                    b.Property<string>("SacramentSong");

                    b.Property<string>("SecondSpeaker");

                    b.Property<string>("ThirdSong");

                    b.HasKey("ID");

                    b.ToTable("Program");
                });
#pragma warning restore 612, 618
        }
    }
}
